stages:
  - deploy

deploy:
  stage: deploy
  script:
    - export PATH=/opt/cpanel/ea-nodejs18/bin/:$PATH
    - bash pm2 kill
    - rm -rf .next
    - git reset --hard || exit 1
    - git clean -df || exit 1
    - git pull origin staging || exit 1  # Make sure to pull from the correct branch
    - bash npm install || exit 1
    - bahs npm run build || exit 1
    - bash pm2 start ./ecosystem.config.js
  only:
    - staging  # Adjust this as necessary to match your branch
