
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import React from "react";
import { CookiesProvider } from "next-client-cookies/server";
import { getCookieServer } from "@/Actions/serverCookies";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: "#fff",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const dir = await getCookieServer("locale");
  return (
    <html lang={dir == "ar" ? "ar" : "en"} dir={dir == "ar" ? "rtl" : "ltr"}>
      <body
        className={inter.className}

      >
        <CookiesProvider>{children}</CookiesProvider>
      </body>
    </html>
  );
}
