import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import React from "react";
import { CookiesProvider } from "next-client-cookies/server";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { locales } from "@/i18m.config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html
      lang={locale == "ar" ? "ar" : "en"}
      dir={locale == "ar" ? "rtl" : "ltr"}
    >
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <CookiesProvider>{children}</CookiesProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
